In [3]:
 import numpy as np

In [6]:
def min_ed_dis(target,source):
    #min_ed_dis - minimum edit distance
    #target- the correct word
    #source- the written word
    
    #Build matric of the correct size
    target = [k for k in target]
    source = [k for k in source]
    sol = np.zeros ((len(source), len(target)))
    
    # first row and column
    sol[0] = [j for j in range(len(target))]
    sol[:,0] = [j for j in range(len(source))]
    
    #Add anchor value
    if target [1] != source[1]:
        sol[1,1] = 2
        
        # Fill in the rest
        
        # Throgh every column
        for c in range (1, len(target)):
            
            # Through every row
            for r in range(1, len(source)):
                
                #Not same letter
                if target[c] != source[r]:
                    sol[r,c] = min(sol[r-1,c],sol[r,c-1]) + 1
                    
                    # Same letter
                else:
                    sol[r,c] = sol[r-1,c-1]
                        
    return sol

In [8]:
min_ed_dis("#target","#source")

array([[0., 1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6., 7.],
       [2., 3., 4., 5., 6., 7., 8.],
       [3., 4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 5., 6., 7., 8.],
       [5., 6., 7., 6., 7., 8., 9.],
       [6., 7., 8., 7., 8., 7., 8.]])

In [7]:
min_ed_dis("#connect","#contact")

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0., 0., 0., 0.],
       [6., 0., 0., 0., 0., 0., 0., 0.],
       [7., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
min_ed_dis(target,source)

NameError: name 'target' is not defined

In [42]:
min_ed_dis("#target","#source")

array([[0., 1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6., 7.],
       [2., 3., 4., 5., 6., 7., 8.],
       [3., 4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 5., 6., 7., 8.],
       [5., 6., 7., 6., 7., 8., 9.],
       [6., 7., 8., 7., 8., 7., 8.]])

In [49]:
min_ed_dis("#connect","#contact")

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0., 0., 0., 0.],
       [6., 0., 0., 0., 0., 0., 0., 0.],
       [7., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
min_ed_dis("#khomo","#paul")

array([[0., 1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6., 7.],
       [3., 4., 5., 6., 7., 8.],
       [4., 5., 6., 7., 8., 9.]])

In [47]:
min_ed_dis("commute","contact")

array([[0., 1., 2., 3., 4., 5., 6.],
       [1., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0., 0., 0.],
       [6., 0., 0., 0., 0., 0., 0.]])

In [48]:
min_ed_dis("contact","lesedi")

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11.]])